<title>Liste des clients</title>
<style>
    table {
        border-collapse: collapse;
        width: 100%;
    }

    th, td {
        border: 1px solid #ddd;
        padding: 8px;
        text-align: left;
    }

    th {
        background-color: #f2f2f2;
    }
</style>
<head>

</head>
<body>
<h1>Liste des clients</h1>

<table>
    <thead>
    <tr>
        <th>ID</th>
        <th>Nom</th>
        <th>Email</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($clients as $client): ?>
        <tr>
            <td><?php echo $client['id']; ?></td>
            <td><?php echo $client['name']; ?></td>
            <td><?php echo $client['command']; ?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

